name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          cat header/Header-Book.md [0-9]*.md > book.md
          cat header/Header-non-Book.md [0-9]*.md > non-book.md
      - uses: docker://pandoc/latex:latest
        with: 
          entrypoint: /bin/sh
          args: |
            -c "wget https://github.com/Wandmalfarbe/pandoc-latex-template/releases/download/v1.6.0/Eisvogel-1.6.0.tar.gz &&
            tar xvzf Eisvogel-1.6.0.tar.gz &&
            mkdir -p ~/.pandoc/templates/ &&
            cp eisvogel.tex ~/.pandoc/templates/eisvogel.latex &&
            apk --update add font-noto font-noto-cjk font-noto-cjk-extra ttf-ubuntu-font-family && 
            tlmgr update --self &&
            tlmgr install ctex fvextra footnotebackref mdframed zref needspace titling pagecolor sourcesanspro sourcecodepro &&
            mkdir output &&
            pandoc --output=output/book.pdf book.md --shift-heading-level-by=-1 --metadata date=\"`date -u '+%Y-%m-%d'`($GITHUB_SHA)\" --template eisvogel --highlight-style kate --pdf-engine=xelatex &&
            pandoc --output=output/non-book.pdf non-book.md --shift-heading-level-by=-1 --metadata date=\"`date -u '+%Y-%m-%d'`($GITHUB_SHA)\" --template eisvogel --highlight-style kate --pdf-engine=xelatex
            "
      - uses: actions/upload-artifact@master
        with:
          name: output
          path: output
